Repository Kek-i/KEKI_Server, pull requests merged in 2023-01, with the labels that each got.

#5 [feature/4-swagger] Swagger API 초기 설정
  build.gradle
  src/main/java/com/codepatissier/keki/calendar/contoller/CalendarController.java
  src/main/java/com/codepatissier/keki/common/config/SwaggerConfig.java
  src/main/java/com/codepatissier/keki/common/config/WebSecurityConfig.java
  src/main/java/com/codepatissier/keki/cs/controller/HideController.java
  src/main/java/com/codepatissier/keki/cs/controller/NoticeController.java
  src/main/java/com/codepatissier/keki/cs/controller/ReportController.java
  src/main/java/com/codepatissier/keki/dessert/controller/DessertController.java
  src/main/java/com/codepatissier/keki/history/controller/HistoryController.java
  src/main/java/com/codepatissier/keki/post/controller/PostController.java
  src/main/java/com/codepatissier/keki/stores/controller/StoreController.java
  src/main/java/com/codepatissier/keki/user/controller/UserController.java
Labels: infra

#13 [feature/1-infra] 프로젝트 예외 처리 기능 추가
  src/main/java/com/codepatissier/keki/common/BaseEntity.java
  src/main/java/com/codepatissier/keki/common/BaseException.java
  src/main/java/com/codepatissier/keki/common/BaseResponse.java
  src/main/java/com/codepatissier/keki/common/BaseResponseStatus.java
Labels: infra

#14 [feature/4-swagger] Swagger WebSecurityConfig 설정 변경
  src/main/java/com/codepatissier/keki/common/config/WebSecurityConfig.java
Labels: infra

#15 [feature/9-histories] 검색 API 생성
  src/main/java/com/codepatissier/keki/common/BaseEntity.java
  src/main/java/com/codepatissier/keki/common/BaseResponseStatus.java
  src/main/java/com/codepatissier/keki/common/Constant.java
  src/main/java/com/codepatissier/keki/history/controller/HistoryController.java
  src/main/java/com/codepatissier/keki/history/dto/PostSearchRes.java
  src/main/java/com/codepatissier/keki/history/dto/SearchRes.java
  src/main/java/com/codepatissier/keki/history/repository/PostHistoryRepository.java
  src/main/java/com/codepatissier/keki/history/repository/SearchHistoryRepository.java
  src/main/java/com/codepatissier/keki/history/service/PostHistoryService.java
  src/main/java/com/codepatissier/keki/history/service/SearchHistoryService.java
  src/main/java/com/codepatissier/keki/post/entity/Post.java
  src/main/java/com/codepatissier/keki/post/entity/PostImg.java
Labels: feature

#16 [feature/4-swagger] Swagger WebSecurityConfig 설정 변경
  src/main/java/com/codepatissier/keki/common/config/WebSecurityConfig.java
Labels: infra

#18 [feature/6-stores-signup] 판매자 회원가입 API
  build.gradle
  src/main/java/com/codepatissier/keki/common/BaseResponseStatus.java
  src/main/java/com/codepatissier/keki/store/controller/StoreController.java
  src/main/java/com/codepatissier/keki/store/dto/PostStoreReq.java
  src/main/java/com/codepatissier/keki/store/entity/Store.java
  src/main/java/com/codepatissier/keki/store/repository/StoreRepository.java
  src/main/java/com/codepatissier/keki/store/service/StoreService.java
  src/main/java/com/codepatissier/keki/stores/controller/StoreController.java
  src/main/java/com/codepatissier/keki/stores/dto/StoreDTO.java
  src/main/java/com/codepatissier/keki/stores/service/StoreService.java
Labels: feature

#20 [feature/12-posts-getposts] 스토어별 피드 목록 조회 API
  src/main/java/com/codepatissier/keki/common/BaseResponseStatus.java
  src/main/java/com/codepatissier/keki/common/Constant.java
  src/main/java/com/codepatissier/keki/post/controller/PostController.java
  src/main/java/com/codepatissier/keki/post/dto/GetPostsRes.java
  src/main/java/com/codepatissier/keki/post/dto/GetStorePostsRes.java
  src/main/java/com/codepatissier/keki/post/dto/PostDTO.java
  src/main/java/com/codepatissier/keki/post/entity/Post.java
  src/main/java/com/codepatissier/keki/post/repository/PostRepository.java
  src/main/java/com/codepatissier/keki/post/service/PostService.java
Labels: 🍰 feature

#22 [feature/1-infra-queryDsl] 프로젝트 초기 설정
  build.gradle
Labels: 🎉 infra

#23 [feature/6-stores-info-fix] orElseThrow() 오류 수정
  src/main/java/com/codepatissier/keki/store/service/StoreService.java
Labels: ♻️ refactor

#24 [Feature/8-users-fix] User 컬럼 수정
  src/main/java/com/codepatissier/keki/user/entity/User.java
Labels: 🔨 fix

#25 [Feature/9-histories-popular-searches] 인기 검색어 api 생성
  src/main/java/com/codepatissier/keki/common/config/QueryDslConfig.java
  src/main/java/com/codepatissier/keki/history/controller/HistoryController.java
  src/main/java/com/codepatissier/keki/history/dto/SearchRes.java
  src/main/java/com/codepatissier/keki/history/repository/SearchHistoryCustom.java
  src/main/java/com/codepatissier/keki/history/repository/SearchHistoryRepository.java
  src/main/java/com/codepatissier/keki/history/repository/SearchHistoryRepositoryImpl.java
  src/main/java/com/codepatissier/keki/history/service/SearchHistoryService.java
Labels: 🍰 feature

#27 [feature/10-calendars-create] 캘린더 생성 api
  src/main/java/com/codepatissier/keki/calendar/contoller/CalendarController.java
  src/main/java/com/codepatissier/keki/calendar/dto/CalendarDTO.java
  src/main/java/com/codepatissier/keki/calendar/dto/CalendarHashTag.java
  src/main/java/com/codepatissier/keki/calendar/dto/CalendarReq.java
  src/main/java/com/codepatissier/keki/calendar/entity/Calendar.java
  src/main/java/com/codepatissier/keki/calendar/entity/CalendarTag.java
  src/main/java/com/codepatissier/keki/calendar/repository/CalendarTagRepository.java
  src/main/java/com/codepatissier/keki/calendar/service/CalendarService.java
  src/main/java/com/codepatissier/keki/common/BaseResponseStatus.java
  src/main/java/com/codepatissier/keki/common/Tag/Tag.java
  src/main/java/com/codepatissier/keki/common/Tag/TagRepository.java
  src/main/java/com/codepatissier/keki/post/entity/PostTag.java
Labels: 🍰 feature

#29 [feature/7-desserts-getdesserts] 스토어 별 desserts 전체 목록 조회 API
  src/main/java/com/codepatissier/keki/common/BaseResponseStatus.java
  src/main/java/com/codepatissier/keki/dessert/controller/DessertController.java
  src/main/java/com/codepatissier/keki/dessert/dto/GetStoreDessertsRes.java
  src/main/java/com/codepatissier/keki/dessert/repository/DessertRepository.java
  src/main/java/com/codepatissier/keki/dessert/service/DessertService.java
Labels: 🍰 feature

#30 [feature/6-stores-profile] 판매자 프로필 조회 API
  src/main/java/com/codepatissier/keki/store/controller/StoreController.java
  src/main/java/com/codepatissier/keki/store/dto/GetProfileRes.java
  src/main/java/com/codepatissier/keki/store/service/StoreService.java
Labels: 🍰 feature

#33 [feature/8-user- signIn] 카카오 로그인 및 회원가입 구현 API
  .gitignore
  build.gradle
  src/main/java/com/codepatissier/keki/common/Role.java
  src/main/java/com/codepatissier/keki/user/controller/UserController.java
  src/main/java/com/codepatissier/keki/user/dto/PostCustomerReq.java
  src/main/java/com/codepatissier/keki/user/dto/PostUserReq.java
  src/main/java/com/codepatissier/keki/user/dto/PostUserRes.java
  src/main/java/com/codepatissier/keki/user/entity/Provider.java
  src/main/java/com/codepatissier/keki/user/entity/User.java
  src/main/java/com/codepatissier/keki/user/repository/UserRepository.java
  src/main/java/com/codepatissier/keki/user/service/AuthService.java
  src/main/java/com/codepatissier/keki/user/service/KakaoService.java
  src/main/java/com/codepatissier/keki/user/service/UserService.java
  src/main/resources/application.properties
Labels: 🍰 feature

#32 [feature/7-desserts-getone] dessert 상세 화면 조회 API
  src/main/java/com/codepatissier/keki/dessert/controller/DessertController.java
  src/main/java/com/codepatissier/keki/dessert/dto/GetDessertRes.java
  src/main/java/com/codepatissier/keki/dessert/repository/DessertRepository.java
  src/main/java/com/codepatissier/keki/dessert/service/DessertService.java
  src/main/java/com/codepatissier/keki/post/repository/PostRepository.java
Labels: 🍰 feature

#36 [feature/1-infra-querydsl-build] Build gradle 설정 변경
  build.gradle
Labels: 🔨 fix

#34 [feature/12-posts-report] 피드 신고 API
  src/main/java/com/codepatissier/keki/common/BaseResponseStatus.java
  src/main/java/com/codepatissier/keki/post/controller/PostController.java
  src/main/java/com/codepatissier/keki/post/dto/PostReportReq.java
  src/main/java/com/codepatissier/keki/post/service/PostService.java
Labels: 🍰 feature

#39 [feature/1-infra-querydsl-build] gradle build 변경
  build.gradle
Labels: 🚑 hotfix

#38 [feature/8-users-signIn] 닉네임 중복 확인 API 추가
  src/main/java/com/codepatissier/keki/common/BaseResponseStatus.java
  src/main/java/com/codepatissier/keki/user/controller/UserController.java
  src/main/java/com/codepatissier/keki/user/dto/PostNicknameReq.java
  src/main/java/com/codepatissier/keki/user/repository/UserRepository.java
  src/main/java/com/codepatissier/keki/user/service/UserService.java
Labels: 🍰 feature

#40 [feature/8-users-signIn] 회원 관련 예외처리 추가
  src/main/java/com/codepatissier/keki/common/BaseResponseStatus.java
  src/main/java/com/codepatissier/keki/user/controller/UserController.java
  src/main/java/com/codepatissier/keki/user/dto/UserDTO.java
  src/main/java/com/codepatissier/keki/user/service/AuthService.java
  src/main/java/com/codepatissier/keki/user/service/UserService.java
Labels: 🍰 feature

#41 [feature/6-stores-singup-fix-2] 판매자 회원가입 API 수정
  src/main/java/com/codepatissier/keki/store/dto/PostStoreReq.java
  src/main/java/com/codepatissier/keki/store/service/StoreService.java
  src/main/java/com/codepatissier/keki/user/entity/User.java
Labels: ♻️ refactor

#42 [feature/8-users-signIn] 구매자 마이페이지 조회 API 추가
  src/main/java/com/codepatissier/keki/user/controller/UserController.java
  src/main/java/com/codepatissier/keki/user/dto/GetProfileRes.java
  src/main/java/com/codepatissier/keki/user/service/UserService.java
Labels: 🍰 feature

#43 [feature/6-stores-signup-fix-2] BaseException catch 수정
  src/main/java/com/codepatissier/keki/store/service/StoreService.java
Labels: ♻️ refactor

#46 [feature/6-stores-info-fix] Token 사용 수정
  src/main/java/com/codepatissier/keki/store/controller/StoreController.java
Labels: ♻️ refactor

#44 [feature/9-histories-token-fix] token으로 api 접근
  src/main/java/com/codepatissier/keki/history/controller/HistoryController.java
Labels: 🔨 fix

#47 [feature/6-stores-profile-fix] Token 사용 수정
  src/main/java/com/codepatissier/keki/store/controller/StoreController.java
Labels: ♻️ refactor

#45 [feature/10-calendars-token-fix] token api로 접근
  src/main/java/com/codepatissier/keki/calendar/contoller/CalendarController.java
Labels: 🔨 fix

#50 [feature/49-cicd] Dockerfile 생성
  Dockerfile
Labels: 🐳 CI/CD

#51 [feature/49-cicd] 도커파일 수정
  Dockerfile
Labels: 🐳 CI/CD

#48 [feature/12-posts-getposts] 스토어별&검색어별&태그별 피드 목록 조회 API
  src/main/java/com/codepatissier/keki/common/BaseResponseStatus.java
  src/main/java/com/codepatissier/keki/common/Tag/Tag.java
  src/main/java/com/codepatissier/keki/post/controller/PostController.java
  src/main/java/com/codepatissier/keki/post/dto/GetPostsRes.java
  src/main/java/com/codepatissier/keki/post/dto/GetStorePostsRes.java
  src/main/java/com/codepatissier/keki/post/entity/Post.java
  src/main/java/com/codepatissier/keki/post/entity/PostTag.java
  src/main/java/com/codepatissier/keki/post/repository/PostLikeRepository.java
  src/main/java/com/codepatissier/keki/post/repository/PostRepository.java
  src/main/java/com/codepatissier/keki/post/repository/PostTagRepository.java
  src/main/java/com/codepatissier/keki/post/service/PostService.java
Labels: 🍰 feature

#53 [feature/12-posts-token-fix] Access Token 적용
  src/main/java/com/codepatissier/keki/post/controller/PostController.java
  src/main/java/com/codepatissier/keki/post/service/PostService.java
Labels: ♻️ refactor

#54 [feature/12-posts-makeHistory] 조회 기록 API
  src/main/java/com/codepatissier/keki/post/controller/PostController.java
  src/main/java/com/codepatissier/keki/post/service/PostService.java
Labels: 🍰 feature

#55 [feature/12-posts-deletePost] 피드 삭제 API
  src/main/java/com/codepatissier/keki/common/BaseResponseStatus.java
  src/main/java/com/codepatissier/keki/post/controller/PostController.java
  src/main/java/com/codepatissier/keki/post/service/PostService.java
Labels: 🍰 feature

#56 [feature/10-calendars-fix-date-format] 데이터 포맷 변경
  src/main/java/com/codepatissier/keki/calendar/dto/CalendarReq.java
Labels: 🔨 fix

#57 [feature/8-users-mypage] 구매자 프로필 수정 API 추가
  src/main/java/com/codepatissier/keki/user/controller/UserController.java
  src/main/java/com/codepatissier/keki/user/dto/PatchProfileReq.java
  src/main/java/com/codepatissier/keki/user/entity/User.java
  src/main/java/com/codepatissier/keki/user/service/UserService.java
Labels: 🍰 feature

#58 [feature/10-calendars-get-calendar] 기념일 하나 조회
  src/main/java/com/codepatissier/keki/calendar/contoller/CalendarController.java
  src/main/java/com/codepatissier/keki/calendar/dto/CalendarRes.java
  src/main/java/com/codepatissier/keki/calendar/service/CalendarService.java
  src/main/java/com/codepatissier/keki/common/BaseResponseStatus.java
  src/main/java/com/codepatissier/keki/common/Tag/Tag.java
Labels: 🍰 feature, 🔨 fix

#65 [feature/8-users-auth] 카카오 로그인 로직 수정
  src/main/java/com/codepatissier/keki/user/controller/UserController.java
  src/main/java/com/codepatissier/keki/user/service/UserService.java
Labels: 🔨 fix

#60 [feature/12-posts-makePost] 피드 등록 API
  src/main/java/com/codepatissier/keki/common/BaseResponseStatus.java
  src/main/java/com/codepatissier/keki/post/controller/PostController.java
  src/main/java/com/codepatissier/keki/post/dto/PostPostReq.java
  src/main/java/com/codepatissier/keki/post/entity/Post.java
  src/main/java/com/codepatissier/keki/post/entity/PostTag.java
  src/main/java/com/codepatissier/keki/post/repository/PostImgRepository.java
  src/main/java/com/codepatissier/keki/post/service/PostService.java
  src/main/java/com/codepatissier/keki/store/repository/StoreRepository.java
  src/main/java/com/codepatissier/keki/user/repository/UserRepository.java
Labels: 🍰 feature

#61 [feature/6-stores-fix] 사업자 정보 조회 API path variable 추가 및 판매자 프로필 조회 API 분리
  src/main/java/com/codepatissier/keki/store/controller/StoreController.java
  src/main/java/com/codepatissier/keki/store/dto/GetMyPageStoreProfileRes.java
  src/main/java/com/codepatissier/keki/store/dto/GetStoreProfileRes.java
  src/main/java/com/codepatissier/keki/store/service/StoreService.java
Labels: 🔨 fix

#62 [feature/6-stores-patchProfile] 판매자 프로필 조회 API
  src/main/java/com/codepatissier/keki/store/controller/StoreController.java
  src/main/java/com/codepatissier/keki/store/dto/PatchProfileReq.java
  src/main/java/com/codepatissier/keki/store/entity/Store.java
  src/main/java/com/codepatissier/keki/store/service/StoreService.java
  src/main/java/com/codepatissier/keki/user/entity/User.java
Labels: 🍰 feature

#64 [feature/7-desserts-addDessert] 디저트 등록 API
  src/main/java/com/codepatissier/keki/dessert/controller/DessertController.java
  src/main/java/com/codepatissier/keki/dessert/dto/PostDessertReq.java
  src/main/java/com/codepatissier/keki/dessert/entity/Dessert.java
  src/main/java/com/codepatissier/keki/dessert/service/DessertService.java
  src/main/java/com/codepatissier/keki/store/entity/Store.java
  src/main/java/com/codepatissier/keki/store/repository/StoreRepository.java
Labels: 🍰 feature

#66 [feature/8-users-fix] 액세스 토큰 만료 시간 임시 수정
  src/main/java/com/codepatissier/keki/user/service/AuthService.java
Labels: 🚑 hotfix

#70 [feature/7-desserts-deleteDessert] 디저트 삭제 API
  src/main/java/com/codepatissier/keki/dessert/controller/DessertController.java
  src/main/java/com/codepatissier/keki/dessert/service/DessertService.java
  src/main/java/com/codepatissier/keki/store/service/StoreService.java
Labels: 🍰 feature

#69 [feature/67-cs-notice] 공지사항 전체/상세 조회 API 추가
  src/main/java/com/codepatissier/keki/common/BaseResponseStatus.java
  src/main/java/com/codepatissier/keki/cs/controller/CsController.java
  src/main/java/com/codepatissier/keki/cs/controller/HideController.java
  src/main/java/com/codepatissier/keki/cs/controller/NoticeController.java
  src/main/java/com/codepatissier/keki/cs/controller/ReportController.java
  src/main/java/com/codepatissier/keki/cs/dto/GetNoticeListRes.java
  src/main/java/com/codepatissier/keki/cs/dto/GetNoticeRes.java
  src/main/java/com/codepatissier/keki/cs/entity/Notice.java
  src/main/java/com/codepatissier/keki/cs/service/CsService.java
  src/main/java/com/codepatissier/keki/cs/service/HideService.java
  src/main/java/com/codepatissier/keki/cs/service/NoticeService.java
  src/main/java/com/codepatissier/keki/cs/service/ReportService.java
Labels: 🍰 feature

#72 [feature/9-histories-union] 인기, 최신 검색어, 최근 본 케이크
  src/main/java/com/codepatissier/keki/history/controller/HistoryController.java
  src/main/java/com/codepatissier/keki/history/dto/HistorySearchRes.java
  src/main/java/com/codepatissier/keki/history/service/PostHistoryService.java
  src/main/java/com/codepatissier/keki/history/service/SearchHistoryService.java
Labels: 🍰 feature

#73 [feature/10-calendars-get-calendar] 날짜수 return 값 변경 및 기념일 리스트 조회 PK 추가
  src/main/java/com/codepatissier/keki/calendar/dto/CalendarListRes.java
  src/main/java/com/codepatissier/keki/calendar/service/CalendarService.java
Labels: 🔨 fix

#74 [feature/8-users-fix] getUserIdx 필수 및 선택으로 분리
  src/main/java/com/codepatissier/keki/common/BaseResponseStatus.java
  src/main/java/com/codepatissier/keki/common/Constant.java
  src/main/java/com/codepatissier/keki/user/service/AuthService.java
Labels: 🍰 feature, 🔨 fix

#75 [feature/12-posts-getposts-fix] getUserIdxOptional로 변경
  src/main/java/com/codepatissier/keki/post/controller/PostController.java
  src/main/java/com/codepatissier/keki/post/dto/GetPostsRes.java
  src/main/java/com/codepatissier/keki/post/service/PostService.java
Labels: ♻️ refactor

#76 [feature/8-users-auth] 네이버 로그인 API 추가
  build.gradle
  src/main/java/com/codepatissier/keki/user/controller/UserController.java
  src/main/java/com/codepatissier/keki/user/dto/NaverLogin.java
  src/main/java/com/codepatissier/keki/user/service/NaverService.java
  src/main/java/com/codepatissier/keki/user/service/UserService.java
Labels: 🍰 feature

#78 [feature/8-users-auth] 카카오 로그인 URL 요청 API 추가
  src/main/java/com/codepatissier/keki/user/controller/UserController.java
  src/main/java/com/codepatissier/keki/user/dto/KakaoLogin.java
  src/main/java/com/codepatissier/keki/user/service/KakaoService.java
Labels: 🍰 feature

#79 [feature/6-stores-fix] orderUrl NotNull 처리 및 modifyProfile refactor
  src/main/java/com/codepatissier/keki/store/entity/Store.java
  src/main/java/com/codepatissier/keki/store/service/StoreService.java
Labels: ♻️ refactor, 🔨 fix

#80 [feature/6-stores-profile-fix] 판매자 프로필 조회 API orderUrl값 추가
  src/main/java/com/codepatissier/keki/store/controller/StoreController.java
  src/main/java/com/codepatissier/keki/store/dto/GetStoreProfileRes.java
  src/main/java/com/codepatissier/keki/store/service/StoreService.java
Labels: 🔨 fix

#81 [feature/6-stores-profile-fix] 마이 페이지 판매자 프로필 조회 API Response 사업자 정보 추가
  src/main/java/com/codepatissier/keki/store/controller/StoreController.java
  src/main/java/com/codepatissier/keki/store/dto/GetMyPageStoreProfileRes.java
  src/main/java/com/codepatissier/keki/store/service/StoreService.java
Labels: ♻️ refactor

#83 [feature/8-users-auth] 구글 로그인 API 추가
  src/main/java/com/codepatissier/keki/user/controller/UserController.java
  src/main/java/com/codepatissier/keki/user/dto/GoogleLogin.java
  src/main/java/com/codepatissier/keki/user/service/GoogleService.java
  src/main/java/com/codepatissier/keki/user/service/UserService.java
Labels: 🍰 feature

#84 [feature/10-calendars-fix-category] 기념일 목록조회 result 변경
  src/main/java/com/codepatissier/keki/calendar/dto/CalendarListRes.java
  src/main/java/com/codepatissier/keki/calendar/service/CalendarService.java
Labels: 🔨 fix

#86 [feature/9-histories-fix-all-of-api] 검색어 통합 api token 없이 접근 가능
  src/main/java/com/codepatissier/keki/history/controller/HistoryController.java
Labels: 🔨 fix

#88 [feature/9-histories-fix-all-of-api] result 결과 값 변경
  src/main/java/com/codepatissier/keki/history/controller/HistoryController.java
Labels: 🔨 fix

#89 [feature/7-desserts-patchDessert] dessert 수정 API
  src/main/java/com/codepatissier/keki/dessert/controller/DessertController.java
  src/main/java/com/codepatissier/keki/dessert/dto/PatchDessertReq.java
  src/main/java/com/codepatissier/keki/dessert/dto/PostDessertReq.java
  src/main/java/com/codepatissier/keki/dessert/entity/Dessert.java
  src/main/java/com/codepatissier/keki/dessert/service/DessertService.java
  src/main/java/com/codepatissier/keki/store/dto/PostStoreReq.java
Labels: 🍰 feature

#90 [feature/7-desserts-fix] Validation 수정 및 dessertPrice 타입 변경
  src/main/java/com/codepatissier/keki/dessert/dto/GetDessertRes.java
  src/main/java/com/codepatissier/keki/dessert/dto/PatchDessertReq.java
  src/main/java/com/codepatissier/keki/dessert/dto/PostDessertReq.java
Labels: 🔨 fix

#91 [feature/11-home-get] 홈 api 생성
  src/main/java/com/codepatissier/keki/calendar/contoller/CalendarController.java
  src/main/java/com/codepatissier/keki/calendar/dto/HomePostRes.java
  src/main/java/com/codepatissier/keki/calendar/dto/HomeRes.java
  src/main/java/com/codepatissier/keki/calendar/dto/HomeTagRes.java
  src/main/java/com/codepatissier/keki/calendar/dto/PopularTagRes.java
  src/main/java/com/codepatissier/keki/calendar/entity/Calendar.java
  src/main/java/com/codepatissier/keki/calendar/repository/Calendar/CalendarCustom.java
  src/main/java/com/codepatissier/keki/calendar/repository/Calendar/CalendarRepository.java
  src/main/java/com/codepatissier/keki/calendar/repository/Calendar/CalendarRepositoryImpl.java
  src/main/java/com/codepatissier/keki/calendar/repository/CalendarTag/CalendarTagCustom.java
  src/main/java/com/codepatissier/keki/calendar/repository/CalendarTag/CalendarTagRepository.java
  src/main/java/com/codepatissier/keki/calendar/repository/CalendarTag/CalendarTagRepositoryImpl.java
  src/main/java/com/codepatissier/keki/calendar/service/CalendarService.java
  src/main/java/com/codepatissier/keki/common/Constant.java
Labels: 🍰 feature

#92 [feature/6-stores-profile-fix] 마이 페이지 판매자 프로필 조회 API Response email 추가
  src/main/java/com/codepatissier/keki/store/controller/StoreController.java
  src/main/java/com/codepatissier/keki/store/dto/GetMyPageStoreProfileRes.java
  src/main/java/com/codepatissier/keki/store/service/StoreService.java
Labels: 🔨 fix

#93 [feature/7-desserts-store-getDessert] 판매자 상품 상세 조회 API
  src/main/java/com/codepatissier/keki/dessert/controller/DessertController.java
  src/main/java/com/codepatissier/keki/dessert/dto/GetStoreDessertRes.java
  src/main/java/com/codepatissier/keki/dessert/service/DessertService.java
Labels: 🍰 feature

#95 [feature/8-users-auth] 회원 탈퇴&로그아웃 API 추가
  src/main/java/com/codepatissier/keki/common/Role.java
  src/main/java/com/codepatissier/keki/user/controller/UserController.java
  src/main/java/com/codepatissier/keki/user/dto/GoogleLogin.java
  src/main/java/com/codepatissier/keki/user/entity/Provider.java
  src/main/java/com/codepatissier/keki/user/entity/User.java
  src/main/java/com/codepatissier/keki/user/service/GoogleService.java
  src/main/java/com/codepatissier/keki/user/service/UserService.java
Labels: 🍰 feature

#94 [feature/8-users-mypage] 구매자 마이페이지 조회 response email 추가
  src/main/java/com/codepatissier/keki/user/dto/GetProfileRes.java
  src/main/java/com/codepatissier/keki/user/service/UserService.java
Labels: 🔨 fix

#96 [feature/10-calendars-get-categories] 카테고리 status 추가
  src/main/java/com/codepatissier/keki/calendar/service/CalendarService.java
  src/main/java/com/codepatissier/keki/common/Tag/Tag.java
  src/main/java/com/codepatissier/keki/common/Tag/TagRepository.java
Labels: 🍰 feature, 🔨 fix

#97 [feature/1-infra] DB 시간 변경
  src/main/resources/application.properties
Labels: 🔨 fix

#101 [feature/8-users-auth] 소셜 로그인 API 로직 서버와 클라이언트 담당 분리
  src/main/java/com/codepatissier/keki/common/BaseResponseStatus.java
  src/main/java/com/codepatissier/keki/user/controller/UserController.java
  src/main/java/com/codepatissier/keki/user/dto/PostUserReq.java
  src/main/java/com/codepatissier/keki/user/entity/Provider.java
  src/main/java/com/codepatissier/keki/user/repository/UserRepository.java
  src/main/java/com/codepatissier/keki/user/service/UserService.java
Labels: 🔨 fix

#98 [feature/6-stores] 판매자 프로필 수정 API empty string, 공백 예외 처리 & 판매자 회원가입, 프로필 수정 API empty string을 null로 변환해 DB 저장
  src/main/java/com/codepatissier/keki/common/BaseResponseStatus.java
  src/main/java/com/codepatissier/keki/common/EmptyStringToNullConverter.java
  src/main/java/com/codepatissier/keki/store/controller/StoreController.java
  src/main/java/com/codepatissier/keki/store/dto/PatchProfileReq.java
  src/main/java/com/codepatissier/keki/store/dto/PostStoreReq.java
  src/main/java/com/codepatissier/keki/store/entity/Store.java
  src/main/java/com/codepatissier/keki/store/service/StoreService.java
Labels: 🔨 fix

#100 [feature/7-desserts] Dessert status 추가
  src/main/java/com/codepatissier/keki/dessert/repository/DessertRepository.java
  src/main/java/com/codepatissier/keki/dessert/service/DessertService.java
  src/main/java/com/codepatissier/keki/post/repository/PostRepository.java
Labels: 🔨 fix

#102 [feature/8-users-auth] 소셜 로그인 API 로직 서버와 클라이언트 담당 분리
  src/main/java/com/codepatissier/keki/common/BaseResponseStatus.java
  src/main/java/com/codepatissier/keki/common/Role.java
  src/main/java/com/codepatissier/keki/user/controller/UserController.java
  src/main/java/com/codepatissier/keki/user/dto/PostUserReq.java
  src/main/java/com/codepatissier/keki/user/entity/Provider.java
  src/main/java/com/codepatissier/keki/user/entity/User.java
  src/main/java/com/codepatissier/keki/user/repository/UserRepository.java
  src/main/java/com/codepatissier/keki/user/service/UserService.java
Labels: 🔨 fix

#99 [feature/10-calendars-create-every-year] 매년 반복 기능 추가
  src/main/java/com/codepatissier/keki/calendar/contoller/CalendarController.java
  src/main/java/com/codepatissier/keki/calendar/entity/Calendar.java
  src/main/java/com/codepatissier/keki/calendar/service/CalendarService.java
Labels: 🍰 feature, 🔨 fix

#103 [feature/7-desserts] Dessert 수정 API empty string 예외 처리 및 user, store status 추가
  src/main/java/com/codepatissier/keki/common/BaseResponseStatus.java
  src/main/java/com/codepatissier/keki/dessert/dto/DessertDTO.java
  src/main/java/com/codepatissier/keki/dessert/dto/PatchDessertReq.java
  src/main/java/com/codepatissier/keki/dessert/entity/Dessert.java
  src/main/java/com/codepatissier/keki/dessert/service/DessertService.java
  src/main/java/com/codepatissier/keki/store/repository/StoreRepository.java
Labels: ♻️ refactor, 🔨 fix

#104 [feature/6-stores] user, store status 추가
  src/main/java/com/codepatissier/keki/store/service/StoreService.java
Labels: 🔨 fix

#105 [feature/10-calendars-status-change] status 추가
  src/main/java/com/codepatissier/keki/calendar/repository/Calendar/CalendarRepository.java
  src/main/java/com/codepatissier/keki/calendar/repository/Calendar/CalendarRepositoryImpl.java
  src/main/java/com/codepatissier/keki/calendar/repository/CalendarTag/CalendarTagRepositoryImpl.java
  src/main/java/com/codepatissier/keki/calendar/service/CalendarService.java
Labels: 🍰 feature, 🔨 fix

#106 [feature/8-users-auth] user status 추가
  src/main/java/com/codepatissier/keki/common/Constant.java
  src/main/java/com/codepatissier/keki/user/entity/User.java
  src/main/java/com/codepatissier/keki/user/repository/UserRepository.java
  src/main/java/com/codepatissier/keki/user/service/UserService.java
Labels: ♻️ refactor, 🔨 fix

#108 [feature/10-calendars-status-change] 기념일 status 추가
  src/main/java/com/codepatissier/keki/calendar/repository/Calendar/CalendarRepository.java
  src/main/java/com/codepatissier/keki/calendar/service/CalendarService.java
Labels: 🔨 fix

#107 [feature/67-cs-notice] 공지사항 status 추가
  src/main/java/com/codepatissier/keki/cs/repository/NoticeRepository.java
  src/main/java/com/codepatissier/keki/cs/service/CsService.java
Labels: 🔨 fix

#110 [feature/10-calendars-fix-date-format] 매년 반복 로직 생성
  src/main/java/com/codepatissier/keki/calendar/service/CalendarService.java
Labels: 🍰 feature, 🔨 fix

#112 [feature/11-home-get] 홈 api 판매자 가게 이름 추가
  src/main/java/com/codepatissier/keki/calendar/dto/HomePostRes.java
  src/main/java/com/codepatissier/keki/calendar/repository/Calendar/CalendarRepositoryImpl.java
Labels: 🔨 fix

#113 [feature/10-calendars-exception] 기념일 api exception 추가
  src/main/java/com/codepatissier/keki/calendar/service/CalendarService.java
Labels: 🔨 fix

#114 [feature/12-posts-getposts] 피드 목록 조회 정렬 기능 추가
  src/main/java/com/codepatissier/keki/common/BaseResponseStatus.java
  src/main/java/com/codepatissier/keki/common/Constant.java
  src/main/java/com/codepatissier/keki/post/controller/PostController.java
  src/main/java/com/codepatissier/keki/post/repository/PostCustom.java
  src/main/java/com/codepatissier/keki/post/repository/PostRepository.java
  src/main/java/com/codepatissier/keki/post/repository/PostRepositoryImpl.java
  src/main/java/com/codepatissier/keki/post/repository/PostTagCustom.java
  src/main/java/com/codepatissier/keki/post/repository/PostTagRepository.java
  src/main/java/com/codepatissier/keki/post/repository/PostTagRepositoryImpl.java
  src/main/java/com/codepatissier/keki/post/service/PostService.java
Labels: 🍰 feature
