Repository Kek-i/KEKI_Server, pull requests merged in 2023-03, with the labels that each got.

#152 [feature/11-home-fix] 홈 api 수정
  src/main/java/com/codepatissier/keki/calendar/DateCountCategory.java
  src/main/java/com/codepatissier/keki/calendar/contoller/CalendarController.java
  src/main/java/com/codepatissier/keki/calendar/dto/CalendarDateReturn.java
  src/main/java/com/codepatissier/keki/calendar/dto/HomeRes.java
  src/main/java/com/codepatissier/keki/calendar/repository/CalendarTag/CalendarTagCustom.java
  src/main/java/com/codepatissier/keki/calendar/repository/CalendarTag/CalendarTagRepositoryImpl.java
  src/main/java/com/codepatissier/keki/calendar/service/CalendarService.java
Labels: ♻️ refactor, 🔨 fix

#153 [feature/11-home-fix] 계산 문제 에러 해결
  src/main/java/com/codepatissier/keki/calendar/DateCountCategory.java
  src/main/java/com/codepatissier/keki/calendar/service/CalendarService.java
Labels: 🔨 fix

#154 [feature/8-users-auth] 애플 provider 추가
  src/main/java/com/codepatissier/keki/user/entity/Provider.java
Labels: 🍰 feature

#155 [feature/10-calendars-refactor] StringUtils 사용하여 공백 및 null 인 경우 에러 처리
  src/main/java/com/codepatissier/keki/calendar/contoller/CalendarController.java
Labels: 🔨 fix

#156 [feature/7-desserts-getone-fix] 상품 상세 조회 API images 리턴값 상품 상세 이미지(1장)+피드 대표 이미지(최대 4장)로 수정
  src/main/java/com/codepatissier/keki/dessert/dto/GetDessertRes.java
  src/main/java/com/codepatissier/keki/dessert/service/DessertService.java
  src/main/java/com/codepatissier/keki/post/repository/PostRepository.java
Labels: ♻️ refactor, 🔨 fix

#157 [feature/8-users-auth] 로그아웃 api 토큰 관리 추가
  src/main/java/com/codepatissier/keki/common/BaseResponseStatus.java
  src/main/java/com/codepatissier/keki/store/service/StoreService.java
  src/main/java/com/codepatissier/keki/user/entity/User.java
  src/main/java/com/codepatissier/keki/user/service/AuthService.java
  src/main/java/com/codepatissier/keki/user/service/UserService.java
Labels: ♻️ refactor, 🍰 feature, 🔨 fix

#158 [feature/8-users-auth] 회원 탈퇴 api 토큰 관리 추가 및 토큰 예외 처리 추가
  src/main/java/com/codepatissier/keki/common/BaseResponseStatus.java
  src/main/java/com/codepatissier/keki/user/controller/UserController.java
  src/main/java/com/codepatissier/keki/user/entity/User.java
  src/main/java/com/codepatissier/keki/user/service/AuthService.java
  src/main/java/com/codepatissier/keki/user/service/UserService.java
Labels: ♻️ refactor, 🍰 feature

#162 [feature/7-desserts-deleteDessert-fix] 상품 삭제 API 오타 수정
  src/main/java/com/codepatissier/keki/dessert/service/DessertService.java
Labels: 🔨 fix

#163 [feature/161-orders-mvc] 주문 MVC 생성
  src/main/java/com/codepatissier/keki/calendar/entity/CalendarTag.java
  src/main/java/com/codepatissier/keki/calendar/repository/CalendarTag/CalendarTagRepository.java
  src/main/java/com/codepatissier/keki/calendar/repository/CalendarTag/CalendarTagRepositoryImpl.java
  src/main/java/com/codepatissier/keki/calendar/service/CalendarService.java
  src/main/java/com/codepatissier/keki/common/tag/Tag.java
  src/main/java/com/codepatissier/keki/common/tag/TagRepository.java
  src/main/java/com/codepatissier/keki/dessert/entity/Option.java
  src/main/java/com/codepatissier/keki/order/controller/OrderController.java
  src/main/java/com/codepatissier/keki/order/entity/OptionOrder.java
  src/main/java/com/codepatissier/keki/order/entity/Order.java
  src/main/java/com/codepatissier/keki/order/entity/OrderImg.java
  src/main/java/com/codepatissier/keki/order/entity/OrderStatus.java
  src/main/java/com/codepatissier/keki/order/repository/OrderRepository.java
  src/main/java/com/codepatissier/keki/order/service/OrderService.java
  src/main/java/com/codepatissier/keki/post/entity/PostTag.java
  src/main/java/com/codepatissier/keki/post/repository/PostTagCustom.java
  src/main/java/com/codepatissier/keki/post/repository/PostTagRepository.java
  src/main/java/com/codepatissier/keki/post/repository/PostTagRepositoryImpl.java
  src/main/java/com/codepatissier/keki/post/service/PostService.java
Labels: 🎉 infra

#164 [feature/11-home-fix-logout-ver] 홈화면 에러 해결
  src/main/java/com/codepatissier/keki/calendar/service/CalendarService.java
  src/main/java/com/codepatissier/keki/user/service/AuthService.java
Labels: 🔨 fix

#165 [feature/7-desserts-getDessert] 상품 상세 조회 API에 디자인 요금 추가
  src/main/java/com/codepatissier/keki/dessert/dto/GetDessertRes.java
  src/main/java/com/codepatissier/keki/dessert/entity/Option.java
  src/main/java/com/codepatissier/keki/dessert/repository/OptionRepository.java
  src/main/java/com/codepatissier/keki/dessert/service/DessertService.java
Labels: ♻️ refactor, 🍰 feature

#166 [feature/7-desserts-addDessert] [판매자] 상품 등록 API에 디자인 요금 추가
  src/main/java/com/codepatissier/keki/dessert/dto/PostDessertReq.java
  src/main/java/com/codepatissier/keki/dessert/entity/Option.java
  src/main/java/com/codepatissier/keki/dessert/service/DessertService.java
Labels: ♻️ refactor, 🍰 feature

#168 [hotfix-1] hotfix: Option 관련 수정 사항 원상복구
  src/main/java/com/codepatissier/keki/dessert/controller/DessertController.java
  src/main/java/com/codepatissier/keki/dessert/dto/OptionDTO.java
  src/main/java/com/codepatissier/keki/dessert/entity/Option.java
  src/main/java/com/codepatissier/keki/dessert/service/DessertService.java
Labels: 🚑 hotfix

#169 [hotfix-1] Option 관련 추가 수정
  src/main/java/com/codepatissier/keki/dessert/dto/GetDessertRes.java
  src/main/java/com/codepatissier/keki/dessert/service/DessertService.java
Labels: 🚑 hotfix

#170 [feature/7-desserts-getDessert] 상품 상세 조회 API에 디자인 요금 추가
  src/main/java/com/codepatissier/keki/dessert/dto/GetDessertRes.java
  src/main/java/com/codepatissier/keki/dessert/dto/OptionDTO.java
  src/main/java/com/codepatissier/keki/dessert/service/DessertService.java
Labels: ♻️ refactor, 🍰 feature

#171 [feature/161-orders-cancel] 주문 취소 API 추가
  src/main/java/com/codepatissier/keki/common/BaseResponseStatus.java
  src/main/java/com/codepatissier/keki/order/controller/OrderController.java
  src/main/java/com/codepatissier/keki/order/entity/Order.java
  src/main/java/com/codepatissier/keki/order/entity/OrderStatus.java
  src/main/java/com/codepatissier/keki/order/service/OrderService.java
Labels: 🍰 feature, 🍊 Sprint #3

#172 [feature/7-desserts-addDessert] [판매자] 상품 등록 API에 디자인 요금 추가
  src/main/java/com/codepatissier/keki/dessert/dto/PostDessertReq.java
  src/main/java/com/codepatissier/keki/dessert/service/DessertService.java
Labels: ♻️ refactor, 🍰 feature, 🍊 Sprint #3

#173 [hotfix-1] 상품 등록 API 내 option 삭제
  src/main/java/com/codepatissier/keki/dessert/dto/PostDessertReq.java
  src/main/java/com/codepatissier/keki/dessert/service/DessertService.java
Labels: 🚑 hotfix

#174 [feature/161-orders-get] 주문 상세 조회 api
  src/main/java/com/codepatissier/keki/order/controller/OrderController.java
  src/main/java/com/codepatissier/keki/order/dto/GetOptionOrder.java
  src/main/java/com/codepatissier/keki/order/dto/GetOrder.java
  src/main/java/com/codepatissier/keki/order/dto/GetOrderImg.java
  src/main/java/com/codepatissier/keki/order/entity/OptionOrder.java
  src/main/java/com/codepatissier/keki/order/entity/Order.java
  src/main/java/com/codepatissier/keki/order/entity/OrderImg.java
  src/main/java/com/codepatissier/keki/order/repository/OptionOrderRepository.java
  src/main/java/com/codepatissier/keki/order/repository/OrderImgRepository.java
  src/main/java/com/codepatissier/keki/order/service/OrderService.java
Labels: 🍰 feature, 🔨 fix, 🍊 Sprint #3

#175 [feature/161-orders-status] [판매자] 주문 상태 변경 API 추가
  src/main/java/com/codepatissier/keki/common/BaseResponseStatus.java
  src/main/java/com/codepatissier/keki/order/controller/OrderController.java
  src/main/java/com/codepatissier/keki/order/dto/PatchOrderStatusReq.java
  src/main/java/com/codepatissier/keki/order/entity/Order.java
  src/main/java/com/codepatissier/keki/order/service/OrderService.java
Labels: 🍰 feature, 🍊 Sprint #3

#176 [feature/8-users-auth] 유저 로그인 URL 요청 API 삭제
  src/main/java/com/codepatissier/keki/user/controller/UserController.java
  src/main/java/com/codepatissier/keki/user/service/GoogleService.java
  src/main/java/com/codepatissier/keki/user/service/KakaoService.java
  src/main/java/com/codepatissier/keki/user/service/NaverService.java
Labels: ♻️ refactor

#177 [feature/7-desserts-getDessert] 상품 상세 조회 API response값에 optionIdx 추가
  src/main/java/com/codepatissier/keki/dessert/dto/OptionDTO.java
  src/main/java/com/codepatissier/keki/dessert/service/DessertService.java
Labels: 🔨 fix

#179 [feature/161-orders-history] 주문 내역 조회 API 추가
  src/main/java/com/codepatissier/keki/order/controller/OrderController.java
  src/main/java/com/codepatissier/keki/order/dto/GetOrderHistory.java
  src/main/java/com/codepatissier/keki/order/dto/GetOrderHistoryReq.java
  src/main/java/com/codepatissier/keki/order/dto/GetOrderHistoryRes.java
  src/main/java/com/codepatissier/keki/order/dto/NumOfOrder.java
  src/main/java/com/codepatissier/keki/order/repository/OrderRepository.java
  src/main/java/com/codepatissier/keki/order/service/OrderService.java
Labels: 🍰 feature, 🍊 sprint #3

#180 [feature/7-desserts-patchDessert] [판매자] 상품 수정 API에 디자인 요금 추가 구현
  src/main/java/com/codepatissier/keki/common/BaseResponseStatus.java
  src/main/java/com/codepatissier/keki/dessert/dto/OptionDTO.java
  src/main/java/com/codepatissier/keki/dessert/dto/PatchDessertReq.java
  src/main/java/com/codepatissier/keki/dessert/dto/PostDessertReq.java
  src/main/java/com/codepatissier/keki/dessert/entity/Option.java
  src/main/java/com/codepatissier/keki/dessert/repository/OptionRepository.java
  src/main/java/com/codepatissier/keki/dessert/service/DessertService.java
Labels: ♻️ refactor, 🍊 sprint #3

#178 [feature/161-orders-get] 주문 화면 조회
  src/main/java/com/codepatissier/keki/order/controller/OrderController.java
  src/main/java/com/codepatissier/keki/order/dto/GetOrderStore.java
  src/main/java/com/codepatissier/keki/order/dto/GetStoreDessertAndOptions.java
  src/main/java/com/codepatissier/keki/order/service/OrderService.java
Labels: 🍰 feature, 🔨 fix, 🍊 sprint #3

#181 [feature/1-infra-create-maindb] main db 생성
  src/main/resources/application.properties
Labels: 🎉 infra

#182 [feature/161-orders-get] 주문 수정 화면 조회 api 생성
  src/main/java/com/codepatissier/keki/order/controller/OrderController.java
  src/main/java/com/codepatissier/keki/order/dto/GetEditOrder.java
  src/main/java/com/codepatissier/keki/order/dto/GetOrder.java
  src/main/java/com/codepatissier/keki/order/service/OrderService.java
Labels: ♻️ refactor, 🍰 feature, 🍊 sprint #3

#186 [feature/184-users-mypage] 마이페이지 조회 API Res 추가
  src/main/java/com/codepatissier/keki/order/service/OrderService.java
  src/main/java/com/codepatissier/keki/user/dto/GetProfileRes.java
  src/main/java/com/codepatissier/keki/user/service/UserService.java
Labels: 🍰 feature, 🍊 sprint #3

#187 [feature/7-desserts-store-getDessert] [판매자] 상품 상세 조회 API 디자인 옵션 추가
  src/main/java/com/codepatissier/keki/dessert/dto/GetStoreDessertRes.java
  src/main/java/com/codepatissier/keki/dessert/service/DessertService.java
Labels: 🍰 feature, 🍊 sprint #3

#188 [feature/161-orders-make] 주문하기 API
  src/main/java/com/codepatissier/keki/common/BaseResponseStatus.java
  src/main/java/com/codepatissier/keki/order/controller/OrderController.java
  src/main/java/com/codepatissier/keki/order/dto/OrderReq.java
  src/main/java/com/codepatissier/keki/order/entity/OptionOrder.java
  src/main/java/com/codepatissier/keki/order/entity/Order.java
  src/main/java/com/codepatissier/keki/order/entity/OrderImg.java
  src/main/java/com/codepatissier/keki/order/repository/OptionOrderRepository.java
  src/main/java/com/codepatissier/keki/order/repository/OrderImgRepository.java
  src/main/java/com/codepatissier/keki/order/service/OrderService.java
Labels: 🍰 feature, 🍊 sprint #3

#191 [develop-sprint-3] 3차 개발 sprint develop 브랜치로 이전
  src/main/java/com/codepatissier/keki/common/BaseResponseStatus.java
  src/main/java/com/codepatissier/keki/dessert/dto/GetDessertRes.java
  src/main/java/com/codepatissier/keki/dessert/dto/GetStoreDessertRes.java
  src/main/java/com/codepatissier/keki/dessert/dto/OptionDTO.java
  src/main/java/com/codepatissier/keki/dessert/dto/PatchDessertReq.java
  src/main/java/com/codepatissier/keki/dessert/entity/Option.java
  src/main/java/com/codepatissier/keki/dessert/repository/OptionRepository.java
  src/main/java/com/codepatissier/keki/dessert/service/DessertService.java
  src/main/java/com/codepatissier/keki/order/controller/OrderController.java
  src/main/java/com/codepatissier/keki/order/dto/GetEditOrder.java
  src/main/java/com/codepatissier/keki/order/dto/GetOptionOrder.java
  src/main/java/com/codepatissier/keki/order/dto/GetOrder.java
  src/main/java/com/codepatissier/keki/order/dto/GetOrderHistory.java
  src/main/java/com/codepatissier/keki/order/dto/GetOrderHistoryReq.java
  src/main/java/com/codepatissier/keki/order/dto/GetOrderHistoryRes.java
  src/main/java/com/codepatissier/keki/order/dto/GetOrderImg.java
  src/main/java/com/codepatissier/keki/order/dto/GetOrderStore.java
  src/main/java/com/codepatissier/keki/order/dto/GetStoreDessertAndOptions.java
  src/main/java/com/codepatissier/keki/order/dto/GetStoreInfo.java
  src/main/java/com/codepatissier/keki/order/dto/GetUserInfo.java
  src/main/java/com/codepatissier/keki/order/dto/NumOfOrder.java
  src/main/java/com/codepatissier/keki/order/dto/OrderReq.java
  src/main/java/com/codepatissier/keki/order/dto/PatchOrderStatusReq.java
  src/main/java/com/codepatissier/keki/order/entity/OptionOrder.java
  src/main/java/com/codepatissier/keki/order/entity/Order.java
  src/main/java/com/codepatissier/keki/order/entity/OrderImg.java
  src/main/java/com/codepatissier/keki/order/entity/OrderStatus.java
  src/main/java/com/codepatissier/keki/order/repository/OptionOrderRepository.java
  src/main/java/com/codepatissier/keki/order/repository/OrderImgRepository.java
  src/main/java/com/codepatissier/keki/order/repository/OrderRepository.java
  src/main/java/com/codepatissier/keki/order/service/OrderService.java
  src/main/java/com/codepatissier/keki/user/dto/GetProfileRes.java
  src/main/java/com/codepatissier/keki/user/service/UserService.java
Labels: 🍰 feature

#192 [feature/6-stores-signup] 판매자 회원가입 API orderUrl 제거 및 예금주, 계좌번호 추가
  src/main/java/com/codepatissier/keki/store/dto/GetMyPageStoreProfileRes.java
  src/main/java/com/codepatissier/keki/store/dto/GetStoreProfileRes.java
  src/main/java/com/codepatissier/keki/store/dto/PostStoreReq.java
  src/main/java/com/codepatissier/keki/store/entity/Store.java
  src/main/java/com/codepatissier/keki/store/service/StoreService.java
Labels: ♻️ refactor, 🍊 sprint #3

#193 [feature/161-orders-fix] Order MultipleBagFetchException 해결 및 BaseEntity 추가
  src/main/java/com/codepatissier/keki/order/entity/Order.java
Labels: 🔨 fix

#195 [feature/161-orders-get] 주문 api 전반적인 리팩토링
  src/main/java/com/codepatissier/keki/order/dto/GetOrderStore.java
  src/main/java/com/codepatissier/keki/order/dto/GetStoreInfo.java
  src/main/java/com/codepatissier/keki/order/service/OrderService.java
Labels: ♻️ refactor, 🍰 feature, 🔨 fix, 🍊 sprint #3

#196 [feature/159-stores-getMypage] [판매자] 판매자 마이페이지 조회 API
  src/main/java/com/codepatissier/keki/store/controller/StoreController.java
  src/main/java/com/codepatissier/keki/store/dto/GetStoreMyPageRes.java
  src/main/java/com/codepatissier/keki/store/service/StoreService.java
Labels: 🍰 feature, 🍊 sprint #3
