Repository Kek-i/KEKI_Server, pull requests merged in 2023-02, with the labels that each got.

#116 [feature/8-users-login-exception] 소셜 로그인 탈퇴 회원 재가입 불가 로직 생성
  src/main/java/com/codepatissier/keki/common/BaseResponseStatus.java
  src/main/java/com/codepatissier/keki/user/repository/UserRepository.java
  src/main/java/com/codepatissier/keki/user/service/UserService.java
Labels: 🔨 fix

#120 [feature/8-users-login-exception] fix: 소셜 로그인 탈퇴 회원 재가입 불가 코드 수정
  src/main/java/com/codepatissier/keki/user/service/UserService.java
Labels: 🔨 fix

#121 [feature/12-posts-like-fix] 피드 목록 조회 내 좋아요 여부 오류 수정
  src/main/java/com/codepatissier/keki/post/repository/PostLikeRepository.java
  src/main/java/com/codepatissier/keki/post/service/PostService.java
Labels: 🔨 fix

#122 [feature/10-calendars-create] 기념일 수정 api 생성
  src/main/java/com/codepatissier/keki/calendar/contoller/CalendarController.java
  src/main/java/com/codepatissier/keki/calendar/dto/CalendarReq.java
  src/main/java/com/codepatissier/keki/calendar/entity/Calendar.java
  src/main/java/com/codepatissier/keki/calendar/repository/CalendarTag/CalendarTagRepository.java
  src/main/java/com/codepatissier/keki/calendar/service/CalendarService.java
  src/main/java/com/codepatissier/keki/common/BaseResponseStatus.java
Labels: 🍰 feature

#123 [feature/12-posts-getone] 개별 피드 조회 API
  src/main/java/com/codepatissier/keki/common/BaseResponseStatus.java
  src/main/java/com/codepatissier/keki/post/controller/PostController.java
  src/main/java/com/codepatissier/keki/post/dto/GetPostRes.java
  src/main/java/com/codepatissier/keki/post/dto/GetPostsRes.java
  src/main/java/com/codepatissier/keki/post/service/PostService.java
Labels: 🍰 feature

#125 [feature/9-histories-union] 검색어 통합 수정
  src/main/java/com/codepatissier/keki/history/repository/PostHistoryCustom.java
  src/main/java/com/codepatissier/keki/history/repository/PostHistoryRepository.java
  src/main/java/com/codepatissier/keki/history/repository/PostHistoryRepositoryImpl.java
  src/main/java/com/codepatissier/keki/history/repository/SearchHistoryCustom.java
  src/main/java/com/codepatissier/keki/history/repository/SearchHistoryRepository.java
  src/main/java/com/codepatissier/keki/history/repository/SearchHistoryRepositoryImpl.java
  src/main/java/com/codepatissier/keki/history/service/PostHistoryService.java
  src/main/java/com/codepatissier/keki/history/service/SearchHistoryService.java
Labels: 🔨 fix

#126 [feature/12-posts-edit-posts] 피드 수정 API
  src/main/java/com/codepatissier/keki/post/controller/PostController.java
  src/main/java/com/codepatissier/keki/post/dto/GetPostRes.java
  src/main/java/com/codepatissier/keki/post/dto/PatchPostReq.java
  src/main/java/com/codepatissier/keki/post/entity/Post.java
  src/main/java/com/codepatissier/keki/post/entity/PostImg.java
  src/main/java/com/codepatissier/keki/post/entity/PostTag.java
  src/main/java/com/codepatissier/keki/post/repository/PostImgRepository.java
  src/main/java/com/codepatissier/keki/post/repository/PostTagRepository.java
  src/main/java/com/codepatissier/keki/post/repository/PostTagRepositoryImpl.java
  src/main/java/com/codepatissier/keki/post/service/PostService.java
Labels: 🍰 feature

#127 [feature/12-posts-getposts-fix] 피드 목록 조회 API 피드 정렬 전체 수정
  src/main/java/com/codepatissier/keki/common/BaseResponseStatus.java
  src/main/java/com/codepatissier/keki/history/repository/PostHistoryRepository.java
  src/main/java/com/codepatissier/keki/post/controller/PostController.java
  src/main/java/com/codepatissier/keki/post/dto/GetPostsRes.java
  src/main/java/com/codepatissier/keki/post/repository/PostCustom.java
  src/main/java/com/codepatissier/keki/post/repository/PostRepository.java
  src/main/java/com/codepatissier/keki/post/repository/PostRepositoryImpl.java
  src/main/java/com/codepatissier/keki/post/repository/PostTagCustom.java
  src/main/java/com/codepatissier/keki/post/repository/PostTagRepositoryImpl.java
  src/main/java/com/codepatissier/keki/post/service/PostService.java
Labels: 🔨 fix

#128 [feature/12-posts-get-like-posts-fix] 좋아요 피드 목록 response 값 변경
  src/main/java/com/codepatissier/keki/post/dto/GetLikePostRes.java
  src/main/java/com/codepatissier/keki/post/dto/GetLikePostsRes.java
  src/main/java/com/codepatissier/keki/post/service/PostService.java
Labels: ♻️ refactor

#129 [feature/6-stores-fix] [판매자] 판매자 프로필 조회 API response에 storeIdx 추가
  src/main/java/com/codepatissier/keki/store/controller/StoreController.java
  src/main/java/com/codepatissier/keki/store/dto/GetMyPageStoreProfileRes.java
  src/main/java/com/codepatissier/keki/store/service/StoreService.java
Labels: 🔨 fix

#130 [feature/12-posts-getposts-fix] GetPostRes에 storeIdx 추가
  src/main/java/com/codepatissier/keki/post/dto/GetPostRes.java
Labels: ♻️ refactor

#131 [12-posts-make-post-view] 피드 등록 화면 API
  src/main/java/com/codepatissier/keki/dessert/repository/DessertRepository.java
  src/main/java/com/codepatissier/keki/post/controller/PostController.java
  src/main/java/com/codepatissier/keki/post/dto/GetMakePostRes.java
  src/main/java/com/codepatissier/keki/post/service/PostService.java
Labels: 🍰 feature

#133 [feature/7-desserts] fix: PostDessertReq valid 처리
  src/main/java/com/codepatissier/keki/dessert/controller/DessertController.java
  src/main/java/com/codepatissier/keki/dessert/dto/PostDessertReq.java
  src/main/java/com/codepatissier/keki/dessert/entity/Dessert.java
Labels: 🔨 fix

#134 [feature/6-stores-fix] fix: 판매자 회원가입 valid 처리
  src/main/java/com/codepatissier/keki/store/dto/PatchProfileReq.java
  src/main/java/com/codepatissier/keki/store/dto/PostStoreReq.java
  src/main/java/com/codepatissier/keki/store/entity/Store.java
  src/main/java/com/codepatissier/keki/store/service/StoreService.java
Labels: 🔨 fix

#137 [feature/7-desserts-store-getDessert-fix] [판매자] 상품 상세 화면 API response에 nickname 추가
  src/main/java/com/codepatissier/keki/dessert/dto/GetStoreDessertRes.java
  src/main/java/com/codepatissier/keki/dessert/service/DessertService.java
Labels: 🔨 fix

#136 [feature/12-posts-getposts-fix] 피드 목록 조회 정렬 오류 수정
  src/main/java/com/codepatissier/keki/post/controller/PostController.java
Labels: 🔨 fix

#138 [feature/12-posts-img-tag-num-fix] 피드 태그, 이미지 개수 조건 추가
  src/main/java/com/codepatissier/keki/common/BaseResponseStatus.java
  src/main/java/com/codepatissier/keki/post/controller/PostController.java
Labels: 🔨 fix

#139 [feature/10-calendars-edit-fix] 캘린더 수정 api 수정 + 캘린더 수정 조회 api 생성 + 태그 생성/상태 변경 api 생성
  src/main/java/com/codepatissier/keki/calendar/contoller/CalendarController.java
  src/main/java/com/codepatissier/keki/calendar/dto/CalendarReq.java
  src/main/java/com/codepatissier/keki/calendar/dto/TagStatus.java
  src/main/java/com/codepatissier/keki/calendar/repository/CalendarTag/CalendarTagRepository.java
  src/main/java/com/codepatissier/keki/calendar/service/CalendarService.java
  src/main/java/com/codepatissier/keki/common/BaseResponseStatus.java
  src/main/java/com/codepatissier/keki/common/Tag/TagRepository.java
Labels: 🍰 feature, 🔨 fix

#140 [feature/9-histoires-union] 최근 검색어/게시물 에러 변경
  src/main/java/com/codepatissier/keki/history/repository/PostHistoryRepositoryImpl.java
  src/main/java/com/codepatissier/keki/history/repository/SearchHistoryRepositoryImpl.java
Labels: 🔨 fix

#142 [feature/12-posts-getposts-fix] 피드 목록 조회 최신순 오류 수정
  src/main/java/com/codepatissier/keki/post/controller/PostController.java
Labels: 🔨 fix

#143 [feature/10-calendars-edit-fix] fix: 캘린더 수정 api 해시태그 삭제 로직 변경
  src/main/java/com/codepatissier/keki/calendar/service/CalendarService.java
Labels: 🍰 feature

#145 [feature/10-calendars-edit-fix] 캘린더 수정 파라미터 실수 수정
  src/main/java/com/codepatissier/keki/calendar/service/CalendarService.java
Labels: 🔨 fix

#146 [feature/10-calendars-edit-fix] 홈화면 기념일 로직 변경
  src/main/java/com/codepatissier/keki/calendar/repository/Calendar/CalendarRepositoryImpl.java
  src/main/java/com/codepatissier/keki/calendar/service/CalendarService.java
Labels: 🔨 fix

#147 [feature/10-calendar-edit-fix] 홈화면 기념일 날짜수 계산 변경
  src/main/java/com/codepatissier/keki/calendar/service/CalendarService.java
Labels: 🔨 fix

#148 [test/delete-cascade] 삭제, 탈퇴 cascade 처리
  src/main/java/com/codepatissier/keki/calendar/entity/Calendar.java
  src/main/java/com/codepatissier/keki/calendar/entity/CalendarTag.java
  src/main/java/com/codepatissier/keki/calendar/repository/Calendar/CalendarRepository.java
  src/main/java/com/codepatissier/keki/calendar/repository/CalendarTag/CalendarTagRepository.java
  src/main/java/com/codepatissier/keki/common/BaseResponseStatus.java
  src/main/java/com/codepatissier/keki/common/BeanUtils.java
  src/main/java/com/codepatissier/keki/common/entityListener/CalendarEntityListener.java
  src/main/java/com/codepatissier/keki/common/entityListener/DessertEntityListener.java
  src/main/java/com/codepatissier/keki/common/entityListener/PostEntityListener.java
  src/main/java/com/codepatissier/keki/common/entityListener/StoreEntityListener.java
  src/main/java/com/codepatissier/keki/common/entityListener/UserEntityListener.java
  src/main/java/com/codepatissier/keki/dessert/controller/DessertController.java
  src/main/java/com/codepatissier/keki/dessert/entity/Dessert.java
  src/main/java/com/codepatissier/keki/dessert/repository/DessertRepository.java
  src/main/java/com/codepatissier/keki/dessert/service/DessertService.java
  src/main/java/com/codepatissier/keki/history/entity/PostHistory.java
  src/main/java/com/codepatissier/keki/history/entity/SearchHistory.java
  src/main/java/com/codepatissier/keki/history/repository/PostHistoryRepository.java
  src/main/java/com/codepatissier/keki/history/repository/SearchHistoryRepository.java
  src/main/java/com/codepatissier/keki/post/controller/PostController.java
  src/main/java/com/codepatissier/keki/post/entity/Post.java
  src/main/java/com/codepatissier/keki/post/entity/PostImg.java
  src/main/java/com/codepatissier/keki/post/entity/PostLike.java
  src/main/java/com/codepatissier/keki/post/entity/PostTag.java
  src/main/java/com/codepatissier/keki/post/repository/PostLikeRepository.java
  src/main/java/com/codepatissier/keki/post/repository/PostRepository.java
  src/main/java/com/codepatissier/keki/post/service/PostService.java
  src/main/java/com/codepatissier/keki/store/entity/Store.java
  src/main/java/com/codepatissier/keki/store/repository/StoreRepository.java
  src/main/java/com/codepatissier/keki/user/entity/User.java
  src/main/java/com/codepatissier/keki/user/service/UserService.java
  src/test/java/com/codepatissier/keki/CascadeTests.java
Labels: 🍰 feature

#149 [feature/12-posts-getposts-fix] 피드 목록 조회 내 dessertIdx 추가
  src/main/java/com/codepatissier/keki/post/dto/GetPostRes.java
Labels: ♻️ refactor

#150 [test/delete-cascade] 삭제, 수정 api 태그&URL 수정
  src/main/java/com/codepatissier/keki/calendar/contoller/CalendarController.java
  src/main/java/com/codepatissier/keki/calendar/service/CalendarService.java
  src/main/java/com/codepatissier/keki/dessert/controller/DessertController.java
  src/main/java/com/codepatissier/keki/history/controller/HistoryController.java
  src/main/java/com/codepatissier/keki/history/service/SearchHistoryService.java
  src/main/java/com/codepatissier/keki/post/controller/PostController.java
  src/main/java/com/codepatissier/keki/user/controller/UserController.java
Labels: ♻️ refactor
